name: Meteo Cron

on:
  schedule:
    - cron: "* * * * *"   # ogni minuto

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Call update.php
        run: curl -A "Mozilla/5.0" "https://cdameteo.altervista.org/meteotemplate/update/update.php?password=Meteo1967template"

  crop:
    runs-on: ubuntu-latest
    steps:
      - name: Call crop_delete.php
        run: curl -A "Mozilla/5.0" "https://cdameteo.altervista.org/cam/crop_delete.php"
